MSA-2025-1/msa-medical

- frontend/package-lock.json
- frontend/package.json
- frontend/src/util/customFetch.js
- frontend/src/util/endpoints.js
- frontend/vite.config.js
- 프론트 dev 서버에 /api 경로에 대해서 http://localhost:8080/ 에 대한 프록시 설정
- endpoint.js
- endpoints.js에 api에 대한 method와 url을 설정해서 모든 api에 대한 설정을 파일 하나에서 처리하도록 한다.
- custom fetch 함수 작성
- axios를 한 번 감싸는 것으로 전체적인 설정을 custom-fetch.js에서 할 수 있도록 한다.
- /api 등 변경될 수 있는 값들을 변수화 필요
> Custom fetch 함수

- server/build.gradle
- server/src/main/resources/application.yml
- MyBatis 사용을 위한 의존성 설정
- datasource 설정
- mapper 폴더 설정
> MyBatis 설정

- server/src/main/java/com/emr/slgi/doctor/DoctorController.java
- server/src/main/java/com/emr/slgi/member/Member.java
- server/src/main/java/com/emr/slgi/member/MemberDAO.java
- server/src/main/java/com/emr/slgi/member/MemberService.java
- server/src/main/resources/application.yml
- server/src/main/resources/mappers/member.xml
- sql/create_member_table.sql
- DoctorController를 작성해서 의사 목록을 가져올 수 있도록 작성
- Member에 대한 테이블 생성 SQL문
- MyBatis에서 케이스 매핑 설정 추가
> 의사 리스트 가져오기 API

- server/.gitignore
- server/src/main/resources/application-db.yml
- server/src/main/resources/application.yml
application-db.yml 파일에 별도 db 환경설정 작성하기.
파일은 Git에 공유하면 gitignore와 상관없이 계속 트래킹되는 문제가 있어 디코 방으로 공유.
> DB 환경설정 별도 분리.

- frontend/src/util/endpoints.js
- server/src/main/java/com/emr/slgi/member/MemberDAO.java
- server/src/main/java/com/emr/slgi/member/dto/MemberSearchDTO.java
- server/src/main/java/com/emr/slgi/patient/PatientController.java
- server/src/main/java/com/emr/slgi/patient/PatientService.java
- server/src/main/java/com/emr/slgi/patient/dto/PatientRegisterDTO.java
- server/src/main/java/com/emr/slgi/patient/dto/PatientSearchDTO.java
- server/src/main/java/com/emr/slgi/staff/StaffController.java
- server/src/main/java/com/emr/slgi/staff/StaffService.java
- server/src/main/resources/mappers/member.xml
- 환자 API
- 환자 검색
- searchValue 쿼리 스트링을 사용해서 환자의 이름에 대해서 검색 가능
- 환자 등록
- 이름, 주민번호, 전화번호를 입력해서 환자 등록(아이디 없이)
- 의료진 API
- 의료진 목록
- 전체 의료진(의사, 간호사) 목록을 가져오도록 함
- 각 API 추가에 대해서 endpoint 추가
> 다른 모듈과의 소통을 위한 Member 관련 API 추가

- frontend/src/components/home/layout/Header.vue
- frontend/src/components/patient/RegisterForm.vue
- frontend/src/router/patientRoutes.js
- frontend/src/util/customFetch.js
- frontend/src/util/endpoints.js
- frontend/src/views/patient/RegisterView.vue
- frontend/src/views/patient/SignupView.vue
- server/src/main/java/com/emr/slgi/auth/AuthController.java
- server/src/main/java/com/emr/slgi/auth/AuthService.java
- server/src/main/java/com/emr/slgi/credentials/CredentialsDAO.java
- server/src/main/resources/mappers/credentials.xml
- 아이디 중복 검사
- 회원가입 입력에 대한 유효성 실시간 검증
> 환자 회원가입 프론트 추가

- frontend/src/util/endpoints.js
- frontend/src/views/regReservationByPatient.vue
fix: endpoint.js에 patient 속성이 팀장님이 만든 것과 내가 만든 부분이 겹치는 문제 해결 및 patient 오타 수정.
patient 속성 중복 내용 삭제.
patient 오타 수정.
> endpoint 부분 중복 문제 해결 및 patient 오타 수정

- frontend/src/util/common.js
- frontend/src/util/endpoints.js
- frontend/src/util/reservation.js
- frontend/src/views/reservation/RegReservationByPatient.vue
- server/src/main/java/com/emr/slgi/reservation/controller/ReservationController.java
- server/src/main/java/com/emr/slgi/reservation/dao/ReservationDAO.java
- server/src/main/java/com/emr/slgi/reservation/dto/FindReservationDate.java
- server/src/main/java/com/emr/slgi/reservation/dto/ReservationForm.java
- server/src/main/java/com/emr/slgi/reservation/service/ReservationService.java
- server/src/main/resources/mappers/reservation.xml
1. toISOString을 이용해 타임존 포함해 돌려주도록 수정.
(안해도 잭슨에서 자동으로 파싱해주나 자동을 너무 믿지는 않기에....)
2. 관련 부분들 수정.
> refactor: LocalDateTime에서 OffsetDateTime으로 타입 변경함에 따라 관련 내용들 수정.

- frontend/src/util/endpoints.js
- frontend/src/util/reservation.js
- frontend/src/views/reservation/RegReservationByPatient.vue
- server/src/main/java/com/emr/slgi/reservation/controller/ReservationController.java
- server/src/main/java/com/emr/slgi/reservation/dao/ReservationDAO.java
- server/src/main/java/com/emr/slgi/reservation/dto/FindReservationDate.java
- server/src/main/java/com/emr/slgi/reservation/dto/ReservationForm.java
- server/src/main/java/com/emr/slgi/reservation/dto/ReservationList.java
- server/src/main/java/com/emr/slgi/reservation/service/ReservationService.java
- server/src/main/java/com/emr/slgi/util/Validate.java
- server/src/main/resources/mappers/reservation.xml
- RegReservationByPatient.vue에서 '취소' 버튼을 누를 경우, 
시간대를 선택해 reservationChk.timeChk가 true면
예약 테이블 내 STATUS를 'RS03' 에서 'RS05' 로 UPDATE 수행.
false일 경우 router.push를 이용해 메인페이지로 이동.
- UPDATE 가 성공하면 router.push를 이용해 메인 페이지로 이동.
- 실패하면 에러 메세지 출력.
- 커밋코드 : d678424(시간대 직렬화 / 역직렬화)
- 서버 내부에서 받을 수 있도록 기존 OffsetDateTime에서 LocalDateTime으로 타입 변경.
- 환자 UUID를 갖고 예약 테이블의 STATUS를 'RS05' 로 UPDATE 수행.
> 예약 홀딩 기능 동작하도록 수정

- frontend/src/router/receptionRoutes.js
> 사용하지 않는 import 제거

- frontend/src/components/diagnosis/VisitHistory.vue
- frontend/src/util/endpoints.js
- server/src/main/java/com/emr/slgi/attachment/AttachmentController.java
- server/src/main/java/com/emr/slgi/page/PageDTO.java
- server/src/main/java/com/emr/slgi/page/PageRequestDTO.java
- server/src/main/java/com/emr/slgi/page/PageResponseDTO.java
- server/src/main/java/com/emr/slgi/page/TreatmentHitoryRequestDTO.java
- server/src/main/java/com/emr/slgi/treatment/TreatmentController.java
- server/src/main/java/com/emr/slgi/treatment/TreatmentDAO.java
- server/src/main/java/com/emr/slgi/treatment/TreatmentService.java
- server/src/main/resources/mappers/treatment/treatment.xml
> 진료 내역 기록 페이징 기능 추가

- frontend/src/auth/accessToken.js
- frontend/src/auth/components/LogoutButton.vue
- frontend/src/auth/refreshToken.js
- frontend/src/components/home/layout/Header.vue
- frontend/src/util/endpoints.js
- server/build.gradle
- server/src/main/java/com/emr/slgi/auth/controller/AuthController.java
- server/src/main/java/com/emr/slgi/auth/dto/LogoutDTO.java
- server/src/main/java/com/emr/slgi/auth/filter/JwtAuthenticationFilter.java
- server/src/main/java/com/emr/slgi/auth/service/AuthService.java
- server/src/main/java/com/emr/slgi/auth/service/RefreshTokenService.java
- server/src/main/java/com/emr/slgi/util/JwtUtil.java
- Redis을 스프링 부트에서 사용하기 위한 Gradle 의존성 추가
- Redis를 도커로 설치하려면 다음 명령어 사용
- `docker pull redis`
- `docker run --name redis -d -p 6379:6379 redis`
- 로그아웃 시에 Redis에 블랙리스트 추가
- 리프레시 토큰으로 액세스 토큰 재발급 시에 블랙리스트를 확인해서 블랙리스트에 있으면 재발급하지 않음
- 로그아웃 시에 pinia의 유저 데이터 제거
> 로그아웃 기능 추가

- frontend/src/util/endpoints.js
- server/src/main/java/com/emr/slgi/auth/controller/AuthController.java
- server/src/main/java/com/emr/slgi/common/dto/ListResponse.java
- server/src/main/java/com/emr/slgi/member/controller/DoctorController.java
- server/src/main/java/com/emr/slgi/member/controller/PatientController.java
- server/src/main/java/com/emr/slgi/member/controller/StaffController.java
- server/src/main/java/com/emr/slgi/member/dao/MemberDAO.java
- server/src/main/java/com/emr/slgi/member/dto/DoctorUuidName.java
- server/src/main/java/com/emr/slgi/member/dto/PatientRegisterDTO.java
- server/src/main/java/com/emr/slgi/member/dto/PatientSearchDTO.java
- server/src/main/java/com/emr/slgi/member/dto/PatientSummary.java
- server/src/main/java/com/emr/slgi/member/dto/StaffSummary.java
- server/src/main/java/com/emr/slgi/member/service/MemberService.java
- server/src/main/resources/mappers/member.xml
- 유효성 검증 추가
- 컨트롤러, 서비스 책임 명확화
- 의료진 인가 동작 추가
- 사용하지 않는 API 제거
- 리스트를 구조를 응답하는 DTO 추가
> Member 모듈 개선

- frontend/src/components/diagnosis/MedicalTreatment.vue
- frontend/src/components/diagnosis/VisitHistory.vue
- frontend/src/components/diagnosis/VisitHistoryDetail.vue
- frontend/src/reception/views/WaitingList.vue
- frontend/src/shared/components/WaitingListPatientList.vue
- frontend/src/util/endpoints.js
- server/src/main/java/com/emr/slgi/payment/PayMent.java
- server/src/main/java/com/emr/slgi/payment/PayMentDAO.java
- server/src/main/java/com/emr/slgi/reception/controller/ReceptionController.java
- server/src/main/java/com/emr/slgi/treatment/Treatment.java
- server/src/main/java/com/emr/slgi/treatment/TreatmentController.java
- server/src/main/java/com/emr/slgi/treatment/TreatmentDAO.java
- server/src/main/java/com/emr/slgi/treatment/TreatmentService.java
- server/src/main/resources/mappers/payment/paymet.xml
- server/src/main/resources/mappers/treatment/treatment.xml
- sql/TB_TREATMENT.sql
- sql/create tb_payment.sql
대기 에서 진료 중 전환 시에 진료 테이블 생성 됨
환자 이름을 누르면 내원 이력을 확인할 수 있다
날짜 클릭시에 write_yn 여부에 따라서 진료 작성 및 이력 상세 보기를 할 수 있다.
진료 완료 버튼을 누르면 진료 완료로 상태 전환이 된다. (접수 테이블)
진료 완료 버튼을 누르면 결재 상태로 전환이 된다.(결재 테이블)
sql문 추가(결재,진료)
-- 결재 금액에 관한 것은 아직 정하진 않음
-- 약 질병 같은 검색해서 넣는 것 개선해야할것 같음 
-- 아직 console 같은건 지우지 않았다
> 상태전환 및 진료 작성 및 결재 상태 전환

- frontend/src/reception/views/AcceptPatientByStaff.vue
- frontend/src/router/index.js
- frontend/src/router/staffRoutes.js
- frontend/src/staff/util/StaffMessage.js
- frontend/src/util/RegexPattern.js
- frontend/src/util/common.js
- frontend/src/util/endpoints.js
- frontend/src/util/regex.js
- frontend/src/views/staff/RegPatientByStaff.vue
- frontend/src/views/staff/StaffMainView.vue
- server/src/main/java/com/emr/slgi/member/controller/PatientController.java
- 이름, 주민번호, 전화번호만 입력 받아 환자 등록 수행.
- 주민번호와 전화번호는 watch를 이용한 정규식으로 실시간 검증 수행.
- 형식이 맞지 않으면 customFetch 동작하지 않도록 구현.
- 이름 길이는 임의로 최소 1자에서 최대 6자로 규정.
- 팀장님께 PatientController 내 registerByStaff 에서 
환자 중복 등록 관련 예외처리 구현 요청.
> 의료진의 환자 등록 기능 구현

- frontend/src/main.js
- 프로필 가져오기에서 에러 발생 시에 이후 진행이 안 되는 문제 해결
> main.js 실행 시에 프로필 가져오기 에러 잡기

- frontend/src/router/patientRoutes.js
- frontend/src/router/reservationRoutes.js
> 기존 reservationRoutes 의 경로를 patientRoutes로 이동

- server/src/main/resources/mappers/attachment/attachment.xml
- server/src/main/resources/mappers/chat/chatMessage.xml
- server/src/main/resources/mappers/chat/chatRead.xml
- server/src/main/resources/mappers/chat/chatroom.xml
- server/src/main/resources/mappers/diagnosis/diagnosis.xml
- server/src/main/resources/mappers/disease/disease.xml
- server/src/main/resources/mappers/medicine/medicine.xml
- server/src/main/resources/mappers/payment/paymet.xml
- server/src/main/resources/mappers/prescription/prescription.xml
- server/src/main/resources/mappers/treatment/treatment.xml
> 디비 테이블 명 대문자로 수정

- server/src/main/java/com/emr/slgi/reservation/dao/ReservationDAO.java
> parm 추가했습니다(이클립스 연결 문제)

- frontend/src/util/errorMessage.js
- frontend/src/views/staff/Search.vue
- 검색 결과가 없을 경우, "검색결과가 존재하지 않습니다." 라는 문구 출력.
-  검색어 입력 후 엔터키로 검색 구현
- length 이용해 빈 값인지 검증 수행하고, 
빈 값이면 "검색어는 최소 1자이상 입력해주세요."라는 문구 알림창으로 출력.
- errorMessage.js 에 해당 문구 별도로 분리해 작성.
> 검색 관련 기능 추가

- frontend/src/staff/components/StaffMenuBar.vue
- 팀장님이 구현한 LogOutButton.vue 를 StaffLayOut.vue 에 컴포넌트로 추가.
- 로그아웃 동작 확인.
- CSS 회의 후 변경 가능.
> 의료진 로그아웃 추가

- frontend/src/router/staffRoutes.js
- frontend/src/staff/components/StaffMenuBar.vue
- frontend/src/staff/layouts/StaffLayOut.vue
- frontend/src/staff/views/RegPatientByStaff.vue
- StaffLayOut.vue 부모 컴포넌트가 별도로 필요하고, 구조를 생각했을 때
가능은 하겠지만 시간 대비 성과의 문제도 있어 일반 Vue 로 리팩토링해 사용하기로 결정.
- StaffLayOut.vue 의 기본 라우터 이용해 환자 등록도 보여주도록 수정.
> 모달에서 일반 Vue 로 변경

- frontend/src/assets/css/ReservationListByStaff.css
- frontend/src/assets/css/StaffMenuBar.css
- frontend/src/assets/css/WaitingStatus.css
- frontend/src/assets/css/waitingreservaion.css
- frontend/src/reception/components/WaitingList.vue
- frontend/src/staff/components/StaffMenuBar.vue
- 병원 로고 메뉴바에 추가.
- 관련 CSS 수정.
- 드롭다운 색깔 수정.
- 너비 등 수정.
> 사이드 바 CSS 수정

- frontend/src/assets/css/StaffLayOut.css
- Header 부터 Footer 까지 임시로 Viewport에 다 보이도록 vh 수정.
> 의료진 메인 Viewport 에 보이도록 임시 수정

- frontend/src/reservation/util/reservation.js
- 예약 성공 시 라우터 수정.
- 기존 환자 메인 페이지에서 환자 예약 목록 페이지로 이동하도록 라우터 수정.
> 예약 완료 시 라우터 수정

- frontend/src/assets/css/Payment.css
- frontend/src/util/endpoints.js
> css 파일에 payment 명 붙여주기

- frontend/src/common/components/Input.vue
- frontend/src/common/components/InvalidityMessage.vue
- frontend/src/common/components/Label.vue
- frontend/src/patient/components/RegisterForm.vue
- frontend/src/patient/components/SectionDivider.vue
- frontend/src/patient/components/Title.vue
- frontend/src/patient/components/UpdateProfileForm.vue
- frontend/src/patient/views/LoginView.vue
- frontend/src/patient/views/MyPageView.vue
- frontend/src/patient/views/RegisterView.vue
- frontend/src/patient/views/UpdateProfile.vue
> 공통 부분 컴포넌트화, 중복 체크 유효성 검사 수정

- frontend/src/router/index.js
- frontend/src/router/patientRoutes.js
- frontend/src/router/staffRoutes.js
- frontend/src/util/customFetch.js
라우터에서 `meta`에 `requiresAuth`, `roles`를 추가하는 것으로 역할에 따라 접근할 수 있는 경로 처리
혹시라도 겹칠 수 있는 속성에 대해서 심볼을 사용해서 처리
> 환자페이지 프론트엔드 개선

- server/src/main/java/com/emr/slgi/reservation/dao/ReservationDAO.java
- server/src/main/java/com/emr/slgi/reservation/service/ReservationService.java
- server/src/main/resources/mappers/reservation/reservation.xml
- 의사 A 기준 이미 예약된 시간대일 경우, 의사 B 도 같은 시간대 선택해 예약하면 이미 예약된 시간이라고 출력되는 문제.
- 의사 UUID 도 비교 기준에 포함해 해결.
- 의사별로 예약 가능 시간대 판별 가능.
> 예약 시 충돌 문제 긴급 수정

- .github/workflows/deployment.yml
- docker-compose.yml
- frontend/nginx.conf
- frontend/src/components/chat/ChatRoom.vue
- server/src/main/java/com/emr/slgi/attachment/AttachmentController.java
- server/src/main/java/com/emr/slgi/attachment/AttachmentService.java
- server/src/main/java/com/emr/slgi/chat/DAO/ChatMessageDAO.java
- server/src/main/java/com/emr/slgi/chat/service/ChatMessageService.java
- server/src/main/java/com/emr/slgi/chat/service/ChatService.java
- server/src/main/resources/application.yml
- server/src/main/resources/mappers/chat/chatMessage.xml
> 환경 변수 기반 이미지 처리 

- frontend/src/patient/components/RegisterForm.vue
> 회원가입에 플레이스홀더 추가

- .github/workflows/deployment.yml
- Docker 이미지와 컨테이너 삭제 명시적으로 수행.
> 사용하지 않는 이미지와 컨테이너 정리 추가

- frontend/src/auth/components/LogoutButton.vue
- frontend/src/util/stompMethod.js
> docs : 로그아웃시 연결 해제

- server/src/main/java/com/emr/slgi/auth/service/AuthService.java
- server/src/main/java/com/emr/slgi/exception/GlobalExceptionHandler.java
- server/src/main/java/com/emr/slgi/member/controller/PatientController.java
> API 응답 메세지 추가
